@BASE_URI=https://solarapimuat.azure-api.net
# public-v1
@VERSION=preview-v1


### Preview version
GET {{BASE_URI}}/software-version 
api-version: preview-v1

### GA version
GET {{BASE_URI}}/software-version 
api-version: public-v1



### List TODO
GET {{BASE_URI}}/todo 
api-version: {{VERSION}}


### Create TODO
POST {{BASE_URI}}/todo 
Content-Type: application/json
api-version: {{VERSION}}

{ "title":"Todo3","summary":"Some text","dueDate":"2025-02-20T07:18:22.2958019+00:00","completed":false}


### Update TODO
POST {{BASE_URI}}/todo 
Content-Type: application/json
api-version: {{VERSION}}

{"id":3,"title":"Todo3","summary":"Some text","dueDate":"2025-02-20T07:18:22.2958019+00:00","completed":false}