
trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "api-management-demo" 
 location: "westeurope"
 APP_NAME: "solar"
 APP_ENV: "uat"


stages:
  - stage: CreateInfrastructure
    displayName: 'Create Infrastructure'    
    jobs:
    - job: CreateInfra
      displayName: Provision or update resources                  
      steps:
      - checkout: self
      - bash: 'az login --service-principal -u $(sp_client_id) -p $(sp_client_secret) --tenant $(sp_tenant_id)'
        displayName: 'Login to Azure'
      - task: Bash@3
        displayName: 'Deploy infrastructure'
        inputs:
          targetType: filePath
          filePath: 'src/Infrastructure/Scripts/create-core-infra.sh'
          workingDirectory: src/Infrastructure/Platform
        env:
          APP_NAME: $(APP_NAME)
          APP_ENV: $(APP_ENV)
          resourceGroupName: $(resourceGroupName)
          location: $(location)                  
