trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "api-management-demo"
 location: "westeurope"
 APP_NAME: "solar"
 APP_ENV: "dev"
 acaEnvName: "$(APP_NAME)-appenv-$(APP_ENV)" 
 imageName: "todo-api"
 tag: "$(Build.BuildId)"
 containerRegistryName: "$(APP_NAME)contregistry$(APP_ENV)"
 registry: "$(containerRegistryName).azurecr.io" 
 

stages:
  # - stage: BuildContainer
  #   displayName: 'Build Container and pushes to registry'
  #   jobs:
  #   - job: Build
  #     displayName: 'Build Job'
  #     steps:
  #     - checkout: self
  #     - task: AzureCLI@2
  #       displayName: Build docker image for TODO API and push to Azure container registry 
  #       inputs:
  #         azureSubscription: 'MCAPS-Hybrid-REQ-38041-2022-MoimHossain'
  #         scriptType: 'bash'
  #         scriptLocation: 'scriptPath'
  #         workingDirectory: 'src/TodoApi'
  #         scriptPath: 'src/Infrastructure/Scripts/build-containers.sh'
  #       env:
  #           imageName: $(imageName)
  #           tag: $(tag)
  #           registry: $(registry)
            

  - stage: DeployToDoApiStage
    displayName: 'Deploy ToDo API'
    jobs:
      - deployment: DeployToDoApiJob
        displayName: 'Deploy ToDo API'
        environment: AEGIS-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Deploy containerapp to ACA
                  inputs:
                    azureSubscription: 'MCAPS-Hybrid-REQ-38041-2022-MoimHossain'
                    scriptType: 'bash'
                    scriptLocation: 'scriptPath'
                    #workingDirectory: 'src/Infrastructure/Containers'
                    scriptPath: 'src/Infrastructure/Scripts/deploy-containerapp.sh'
                  env:
                    APP_NAME: $(APP_NAME)
                    APP_ENV: $(APP_ENV)
                    imageName: $(imageName)
                    tagName: '1593' # $(tag)
                    location: $(location)
                    resourceGroupName: $(resourceGroupName)                
                # - task: AzureCLI@2
                #   displayName: Update API management
                #   inputs:
                #     azureSubscription: 'MCAPS-Hybrid-REQ-38041-2022-MoimHossain'
                #     scriptType: 'bash'
                #     scriptLocation: 'scriptPath'
                #     scriptPath: 'Infrastructure/scripts/update-api.sh'
                #   env:
                #     primaryMode: "no"
                #     APP_NAME: $(APP_NAME)
                #     APP_ENV: $(APP_ENV)
                #     imageName: $(imageName)
                #     tag: $(tag)
                #     location: $(location)
                #     resourceGroupName: $(resourceGroupName)