trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "api-management-demo"
 location: "westeurope"
 APP_NAME: "solar"
 APP_ENV: "uat"
 acaEnvName: "$(APP_NAME)-appenv-$(APP_ENV)" 
 imageName: "todo-api"
 
stages:
  - stage: PromoteAPI
    displayName: 'Promotes the API version'
    jobs:
    - job: PromoteAPI
      displayName: 'Promote API as Public Release'
      steps:
      - checkout: self
      - bash: 'az login --service-principal -u $(sp_client_id) -p $(sp_client_secret) --tenant $(sp_tenant_id)'
      - task: Bash@3
        displayName: Promotes the latest preview as Public Release
        inputs:
          targetType: filePath
          filePath: 'src/Infrastructure/Scripts/promote-api.sh'
          workingDirectory: 'src/Infrastructure/Scripts'
        env:
          primaryMode: "Yes"
          APP_NAME: $(APP_NAME)
          APP_ENV: $(APP_ENV)
          imageName: $(imageName)
          location: $(location)
          resourceGroupName: $(resourceGroupName)