trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "api-management-demo"
 location: "westeurope"
 APP_NAME: "solar"
 APP_ENV: "dev"
 acaEnvName: "$(APP_NAME)-appenv-$(APP_ENV)" 
 imageName: "todo-api"
 
stages:
  - stage: PromoteAPI
    displayName: 'Promotes the API version'
    jobs:
    - job: PromoteAPI
      displayName: 'Promote API as Public Release'
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Promotes the latest preview as Public Release
        inputs:
          azureSubscription: 'MCAPS-Hybrid-REQ-38041-2022-MoimHossain'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: 'src/Infrastructure/Scripts/promote-api.sh'
        env:
          primaryMode: "Yes"
          APP_NAME: $(APP_NAME)
          APP_ENV: $(APP_ENV)
          imageName: $(imageName)
          location: $(location)
          resourceGroupName: $(resourceGroupName)